window.TIP_LIBRARY_DATA = [
  {
    "id": "SW-001",
    "name": "Rope Swing Drill",
    "dimension": "Swing",
    "category": "Tempo",
    "area": "Full Swing",
    "goal": "Calm tempo",
    "location": "Home/Range",
    "time": "5-10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-002",
    "name": "Pause at Top",
    "dimension": "Swing",
    "category": "Tempo",
    "area": "Full Swing",
    "goal": "Control transition",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-003",
    "name": "Smooth 7i Tempo",
    "dimension": "Swing",
    "category": "Tempo",
    "area": "Approach",
    "goal": "Rhythm control",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-004",
    "name": "Step Through",
    "dimension": "Swing",
    "category": "Transition",
    "area": "Full Swing",
    "goal": "Pressure shift",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-005",
    "name": "Hold Finish",
    "dimension": "Swing",
    "category": "Balance",
    "area": "Full Swing",
    "goal": "Stability",
    "location": "Range",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-006",
    "name": "Alignment Stick Box",
    "dimension": "Swing",
    "category": "Setup",
    "area": "All",
    "goal": "Alignment",
    "location": "Range",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-007",
    "name": "Intermediate Target",
    "dimension": "Swing",
    "category": "Setup",
    "area": "All",
    "goal": "Start line",
    "location": "Range",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-008",
    "name": "Ball Position Matrix",
    "dimension": "Swing",
    "category": "Setup",
    "area": "All",
    "goal": "Consistency",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-009",
    "name": "Feet Line Check",
    "dimension": "Swing",
    "category": "Setup",
    "area": "All",
    "goal": "Alignment",
    "location": "Range",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-010",
    "name": "Lead Arm Parallel",
    "dimension": "Swing",
    "category": "Structure",
    "area": "Full Swing",
    "goal": "Length control",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-011",
    "name": "9-to-3 Drill",
    "dimension": "Swing",
    "category": "Structure",
    "area": "Approach",
    "goal": "Compact motion",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-012",
    "name": "Step to Post",
    "dimension": "Swing",
    "category": "Transition",
    "area": "Full Swing",
    "goal": "Lead side stability",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-013",
    "name": "Split Stance Shift",
    "dimension": "Swing",
    "category": "Transition",
    "area": "Full Swing",
    "goal": "Weight transfer",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-014",
    "name": "Lead Leg Brace",
    "dimension": "Swing",
    "category": "Transition",
    "area": "Full Swing",
    "goal": "Post control",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-015",
    "name": "Barrier Drill",
    "dimension": "Swing",
    "category": "Path",
    "area": "Full Swing",
    "goal": "Path control",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-016",
    "name": "Sidearm Throw",
    "dimension": "Swing",
    "category": "Path",
    "area": "Full Swing",
    "goal": "Delivery feel",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-017",
    "name": "Path Gate",
    "dimension": "Swing",
    "category": "Path",
    "area": "Full Swing",
    "goal": "Path awareness",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-018",
    "name": "Start Line Gate",
    "dimension": "Swing",
    "category": "Face",
    "area": "Full Swing",
    "goal": "Face control",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-019",
    "name": "Hold Off Finish",
    "dimension": "Swing",
    "category": "Face",
    "area": "Full Swing",
    "goal": "Reduce hook",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-020",
    "name": "Lead Wrist Control",
    "dimension": "Swing",
    "category": "Face",
    "area": "Full Swing",
    "goal": "Face stability",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-021",
    "name": "Brush After Ball",
    "dimension": "Swing",
    "category": "Strike",
    "area": "Approach",
    "goal": "Low point",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-022",
    "name": "Tee Forward Drill",
    "dimension": "Swing",
    "category": "Strike",
    "area": "Approach",
    "goal": "Strike forward",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-023",
    "name": "Strike Ladder",
    "dimension": "Swing",
    "category": "Strike",
    "area": "Approach",
    "goal": "Consistency",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-024",
    "name": "Heel/Toe Spray",
    "dimension": "Swing",
    "category": "Strike",
    "area": "Full Swing",
    "goal": "Center contact",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-025",
    "name": "Tee Height Ladder",
    "dimension": "Swing",
    "category": "Driver",
    "area": "Off Tee",
    "goal": "Launch control",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-026",
    "name": "Driver Start Line",
    "dimension": "Swing",
    "category": "Driver",
    "area": "Off Tee",
    "goal": "Direction",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-027",
    "name": "Driver Contact Drill",
    "dimension": "Swing",
    "category": "Driver",
    "area": "Off Tee",
    "goal": "Strike height",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SW-028",
    "name": "Fairway Window Drill",
    "dimension": "Swing",
    "category": "Driver",
    "area": "Off Tee",
    "goal": "Playable ball",
    "location": "Range",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SW-029",
    "name": "Half Swing Calibration",
    "dimension": "Swing",
    "category": "Control",
    "area": "Wedges",
    "goal": "Distance control",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SW-030",
    "name": "Tempo Ladder",
    "dimension": "Swing",
    "category": "Tempo",
    "area": "Full Swing",
    "goal": "Rhythm scaling",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-001",
    "name": "Gate Putting Narrow",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "SK-002",
    "name": "Gate Putting Wide",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "SK-003",
    "name": "Chalk Line Drill",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "SK-004",
    "name": "3ft Circle",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-005",
    "name": "3-6-9 Ladder",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-006",
    "name": "Around World",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-007",
    "name": "One Ball Putting",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-008",
    "name": "Restart Ladder",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-009",
    "name": "Lag Ladder",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-010",
    "name": "Leapfrog",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-011",
    "name": "Uphill Lag",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-012",
    "name": "Downhill Lag",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-013",
    "name": "Fringe to Fringe",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-014",
    "name": "Leave Inside 3ft",
    "dimension": "Skill",
    "category": "Putting",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-015",
    "name": "Breaking Clock",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-016",
    "name": "High/Low Read Drill",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-017",
    "name": "Speed Match Drill",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-018",
    "name": "Eyes Closed Pace",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "SK-019",
    "name": "Long Putt Random",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-020",
    "name": "Pre-Round Speed Finder",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "SK-021",
    "name": "6ft Pressure Line",
    "dimension": "Skill",
    "category": "Putting Pressure",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-022",
    "name": "Clock Drill Breaking Putts",
    "dimension": "Skill",
    "category": "Putting Pressure",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-023",
    "name": "Green Speed Calibration Circuit",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-024",
    "name": "One Handed Start Line",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "SK-025",
    "name": "Gate Exit Drill",
    "dimension": "Skill",
    "category": "Putting Pace",
    "area": "Putting",
    "goal": "Improve putting",
    "location": "Green",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "SK-026",
    "name": "Landing Zone Ladder",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-027",
    "name": "Chip & Run Ladder",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-028",
    "name": "High Soft Chip",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-029",
    "name": "Lie Variation Drill",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-030",
    "name": "One Club Chip",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SK-031",
    "name": "Tee Peg Pitch",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Wedges",
    "goal": "Sharpen scoring shots",
    "location": "Range",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SK-032",
    "name": "Sleeve Pitch Drill",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Wedges",
    "goal": "Sharpen scoring shots",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-033",
    "name": "Trajectory Ladder",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-034",
    "name": "Carry Windows",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Wedges",
    "goal": "Sharpen scoring shots",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-035",
    "name": "Par 18 Game",
    "dimension": "Skill",
    "category": "Pitching",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "15",
    "confidence": "Pressure"
  },
  {
    "id": "SK-036",
    "name": "Up & Down Circuit",
    "dimension": "Skill",
    "category": "Pitching",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "15",
    "confidence": "Pressure"
  },
  {
    "id": "SK-037",
    "name": "One Ball Short Game",
    "dimension": "Skill",
    "category": "Pitching",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-038",
    "name": "Miss Zone Drill",
    "dimension": "Skill",
    "category": "Pitching",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-039",
    "name": "Fringe Control",
    "dimension": "Skill",
    "category": "Pitching",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-040",
    "name": "Bump & Run Control",
    "dimension": "Skill",
    "category": "Pitching",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-041",
    "name": "Landing Spot Towel Basic",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "SK-042",
    "name": "Landing Spot Towel Multi-Zone",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-043",
    "name": "First Cut vs Fairway Challenge",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-044",
    "name": "Short Sided Escape",
    "dimension": "Skill",
    "category": "Chipping",
    "area": "Short Game",
    "goal": "Sharpen scoring shots",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-045",
    "name": "Pitch Flight Windows",
    "dimension": "Skill",
    "category": "Pitching",
    "area": "Wedges",
    "goal": "Sharpen scoring shots",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-046",
    "name": "Low Spinner Pitch Rehearsal",
    "dimension": "Skill",
    "category": "Pitching",
    "area": "Wedges",
    "goal": "Sharpen scoring shots",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-047",
    "name": "Wedge Matrix",
    "dimension": "Skill",
    "category": "Wedges",
    "area": "Wedges",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-048",
    "name": "Random Wedges",
    "dimension": "Skill",
    "category": "Wedges",
    "area": "Wedges",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-049",
    "name": "Wedge Ladder",
    "dimension": "Skill",
    "category": "Wedges",
    "area": "Wedges",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-050",
    "name": "Front/Middle/Back",
    "dimension": "Skill",
    "category": "Approach",
    "area": "Approach",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-051",
    "name": "Dispersion Box",
    "dimension": "Skill",
    "category": "Approach",
    "area": "Approach",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-052",
    "name": "Two Club Window",
    "dimension": "Skill",
    "category": "Approach",
    "area": "Approach",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Pressure"
  },
  {
    "id": "SK-053",
    "name": "Center Green Challenge",
    "dimension": "Skill",
    "category": "Approach",
    "area": "Approach",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-054",
    "name": "Fairway Finder",
    "dimension": "Skill",
    "category": "Tee",
    "area": "Off Tee",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-055",
    "name": "Tee Height Ladder",
    "dimension": "Skill",
    "category": "Tee",
    "area": "Off Tee",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-056",
    "name": "One Shot Tee",
    "dimension": "Skill",
    "category": "Tee",
    "area": "Off Tee",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-057",
    "name": "Punch Out Drill",
    "dimension": "Skill",
    "category": "Recovery",
    "area": "Trouble",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-058",
    "name": "Low Punch",
    "dimension": "Skill",
    "category": "Recovery",
    "area": "Trouble",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-059",
    "name": "Curve Around",
    "dimension": "Skill",
    "category": "Recovery",
    "area": "Trouble",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Advanced"
  },
  {
    "id": "SK-060",
    "name": "Trouble to Number",
    "dimension": "Skill",
    "category": "Recovery",
    "area": "Trouble",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-061",
    "name": "Bunker Entry Line",
    "dimension": "Skill",
    "category": "Bunker",
    "area": "Sand",
    "goal": "Improve scoring decisions",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-062",
    "name": "Wedge Distance Combine",
    "dimension": "Skill",
    "category": "Wedges",
    "area": "Wedges",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-063",
    "name": "Grip Down Wedge Map",
    "dimension": "Skill",
    "category": "Wedges",
    "area": "Wedges",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-064",
    "name": "Flighted Wedge Ladder",
    "dimension": "Skill",
    "category": "Wedges",
    "area": "Wedges",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-065",
    "name": "150-199 Window Test",
    "dimension": "Skill",
    "category": "Approach",
    "area": "Approach",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Pressure"
  },
  {
    "id": "SK-066",
    "name": "Approach Randomizer Full Bag",
    "dimension": "Skill",
    "category": "Approach",
    "area": "Approach",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-067",
    "name": "Start Line Window Approach",
    "dimension": "Skill",
    "category": "Approach",
    "area": "Approach",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "15",
    "confidence": "Neutral"
  },
  {
    "id": "SK-068",
    "name": "Eliminate One Side Tee Game",
    "dimension": "Skill",
    "category": "Tee",
    "area": "Off Tee",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-069",
    "name": "Playable Ball Streak",
    "dimension": "Skill",
    "category": "Tee",
    "area": "Off Tee",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Pressure"
  },
  {
    "id": "SK-070",
    "name": "Driver 3W Hybrid Choice Test",
    "dimension": "Skill",
    "category": "Tee",
    "area": "Off Tee",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-071",
    "name": "Fairway Bunker Advance",
    "dimension": "Skill",
    "category": "Bunker",
    "area": "Sand",
    "goal": "Improve scoring decisions",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-072",
    "name": "Tree Window Punch Curve",
    "dimension": "Skill",
    "category": "Recovery",
    "area": "Trouble",
    "goal": "Improve scoring decisions",
    "location": "Range",
    "time": "10",
    "confidence": "Advanced"
  },
  {
    "id": "SK-073",
    "name": "Bunker Dollar Bill",
    "dimension": "Skill",
    "category": "Bunker",
    "area": "Sand",
    "goal": "Improve scoring decisions",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-074",
    "name": "Bunker Carry Ladder",
    "dimension": "Skill",
    "category": "Bunker",
    "area": "Sand",
    "goal": "Improve scoring decisions",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "SK-075",
    "name": "Buried Lie Bunker Escape",
    "dimension": "Skill",
    "category": "Bunker",
    "area": "Sand",
    "goal": "Improve scoring decisions",
    "location": "Short Game Area",
    "time": "10",
    "confidence": "Advanced"
  },
  {
    "id": "MB-001",
    "name": "Cat Cow",
    "dimension": "Mobility",
    "category": "Pelvis",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "3",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-002",
    "name": "Open Books",
    "dimension": "Mobility",
    "category": "T-Spine",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-003",
    "name": "Thread Needle",
    "dimension": "Mobility",
    "category": "T-Spine",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-004",
    "name": "Foam Roller Ext",
    "dimension": "Mobility",
    "category": "T-Spine",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-005",
    "name": "90/90 Hips",
    "dimension": "Mobility",
    "category": "Hips",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-006",
    "name": "Hip Crossovers",
    "dimension": "Mobility",
    "category": "Hips",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-007",
    "name": "Hip Drops",
    "dimension": "Mobility",
    "category": "Hips",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-008",
    "name": "Helicopter Turns",
    "dimension": "Mobility",
    "category": "Pelvis",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-009",
    "name": "Hip Flexor Stretch",
    "dimension": "Mobility",
    "category": "Hips",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-010",
    "name": "Adductor Rockbacks",
    "dimension": "Mobility",
    "category": "Pelvis",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-011",
    "name": "Shoulder Scaption",
    "dimension": "Mobility",
    "category": "Shoulder",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-012",
    "name": "Wall Slides",
    "dimension": "Mobility",
    "category": "Shoulder",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-013",
    "name": "Band Raises",
    "dimension": "Mobility",
    "category": "Shoulder",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-014",
    "name": "Scap Rotation Drill",
    "dimension": "Mobility",
    "category": "Shoulder",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-015",
    "name": "Wrist Flexor Stretch",
    "dimension": "Mobility",
    "category": "Forearm",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "3",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-016",
    "name": "Wrist Extensor Stretch",
    "dimension": "Mobility",
    "category": "Forearm",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "3",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-017",
    "name": "Forearm Rotation",
    "dimension": "Mobility",
    "category": "Forearm",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-018",
    "name": "Ankle Dorsiflexion",
    "dimension": "Mobility",
    "category": "Ankles",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "3",
    "confidence": "Neutral"
  },
  {
    "id": "MB-019",
    "name": "Toe Yoga",
    "dimension": "Mobility",
    "category": "Feet",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "3",
    "confidence": "Neutral"
  },
  {
    "id": "MB-020",
    "name": "Foot Balance Drill",
    "dimension": "Mobility",
    "category": "Feet",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-021",
    "name": "Lead Hip Internal Rotation",
    "dimension": "Mobility",
    "category": "Hips",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-022",
    "name": "Split Stance Pulses",
    "dimension": "Mobility",
    "category": "Pelvis",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-023",
    "name": "Mini Band Shoulder Raise",
    "dimension": "Mobility",
    "category": "Shoulder",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-024",
    "name": "Ankle Rockers",
    "dimension": "Mobility",
    "category": "Ankles",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-025",
    "name": "Standing Torso Turns",
    "dimension": "Mobility",
    "category": "T-Spine",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home/Course",
    "time": "3",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-026",
    "name": "Sun Salutation Flow",
    "dimension": "Mobility",
    "category": "Flow",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-027",
    "name": "Childs Pose Breathing",
    "dimension": "Mobility",
    "category": "Flow",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "MB-028",
    "name": "Worlds Greatest Stretch",
    "dimension": "Mobility",
    "category": "Flow",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home/Course",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-029",
    "name": "Lateral Leg Swings",
    "dimension": "Mobility",
    "category": "Hips",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-030",
    "name": "Torso Twists",
    "dimension": "Mobility",
    "category": "T-Spine",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-031",
    "name": "Handwalks",
    "dimension": "Mobility",
    "category": "Pelvis",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-032",
    "name": "Bird Dogs Mobility",
    "dimension": "Mobility",
    "category": "Pelvis",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "MB-033",
    "name": "Dynamic Side Lunges",
    "dimension": "Mobility",
    "category": "Pelvis",
    "area": "Body",
    "goal": "Improve mobility",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "ST-001",
    "name": "Dead Bug",
    "dimension": "Strength",
    "category": "Core",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-002",
    "name": "Side Plank",
    "dimension": "Strength",
    "category": "Core",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "ST-003",
    "name": "Bird Dog",
    "dimension": "Strength",
    "category": "Core",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-004",
    "name": "Pallof Press",
    "dimension": "Strength",
    "category": "Core",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-005",
    "name": "Split Squat",
    "dimension": "Strength",
    "category": "Lower",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-006",
    "name": "Reverse Lunge",
    "dimension": "Strength",
    "category": "Lower",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-007",
    "name": "Step Up",
    "dimension": "Strength",
    "category": "Lower",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-008",
    "name": "RDL",
    "dimension": "Strength",
    "category": "Hinge",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-009",
    "name": "Single Leg RDL",
    "dimension": "Strength",
    "category": "Hinge",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-010",
    "name": "Glute Bridge",
    "dimension": "Strength",
    "category": "Glutes",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-011",
    "name": "Hip Airplane",
    "dimension": "Strength",
    "category": "Glutes",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Advanced"
  },
  {
    "id": "ST-012",
    "name": "Band Walks",
    "dimension": "Strength",
    "category": "Glutes",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-013",
    "name": "Y-T-I Raises",
    "dimension": "Strength",
    "category": "Scap",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-014",
    "name": "Face Pull",
    "dimension": "Strength",
    "category": "Scap",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-015",
    "name": "Bottoms Up Carry",
    "dimension": "Strength",
    "category": "Scap",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Advanced"
  },
  {
    "id": "ST-016",
    "name": "Farmer Carry",
    "dimension": "Strength",
    "category": "Grip",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-017",
    "name": "Plate Pinch",
    "dimension": "Strength",
    "category": "Grip",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "ST-018",
    "name": "Med Ball Throw",
    "dimension": "Strength",
    "category": "Power",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Advanced"
  },
  {
    "id": "ST-019",
    "name": "Step Behind Throw",
    "dimension": "Strength",
    "category": "Power",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Advanced"
  },
  {
    "id": "ST-020",
    "name": "Broad Jump",
    "dimension": "Strength",
    "category": "Power",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Advanced"
  },
  {
    "id": "ST-021",
    "name": "Suitcase Carry",
    "dimension": "Strength",
    "category": "Core",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-022",
    "name": "Tall Kneeling Pallof",
    "dimension": "Strength",
    "category": "Core",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-023",
    "name": "Front Plank",
    "dimension": "Strength",
    "category": "Core",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-024",
    "name": "Split Squat with Rotation",
    "dimension": "Strength",
    "category": "Glutes",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home/Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-025",
    "name": "Lateral Step Down",
    "dimension": "Strength",
    "category": "Glutes",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "ST-026",
    "name": "Single Leg Bridge",
    "dimension": "Strength",
    "category": "Glutes",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-027",
    "name": "Hip Hinge Dowel",
    "dimension": "Strength",
    "category": "Hinge",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home/Gym",
    "time": "10",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-028",
    "name": "Trap Bar Pull",
    "dimension": "Strength",
    "category": "Hinge",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-029",
    "name": "Goblet Squat",
    "dimension": "Strength",
    "category": "Lower",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Gym",
    "time": "10",
    "confidence": "Neutral"
  },
  {
    "id": "ST-030",
    "name": "Wall Slide Lift Off",
    "dimension": "Strength",
    "category": "Scap",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Neutral"
  },
  {
    "id": "ST-031",
    "name": "Towel Wringing",
    "dimension": "Strength",
    "category": "Grip",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home",
    "time": "5",
    "confidence": "Rebuild"
  },
  {
    "id": "ST-032",
    "name": "Pronation Supination Load",
    "dimension": "Strength",
    "category": "Grip",
    "area": "Body",
    "goal": "Build stability and strength",
    "location": "Home/Gym",
    "time": "10",
    "confidence": "Neutral"
  }
];